POST http://localhost:3000/direct-debit/payment-host-to-host/
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "partnerReferenceNo": "hahe",
  "amount": 8000,
  "currency": "IDR"
}